> **Atividade** (Sendo aprimorada):
> 1. Adapte o código acima para fazer com que a função `solve_triangular_superior()` também retorno o número de operações (somas, produtos, divisões e subtrações numéricas) que foram realizadas. (**Dica**: A resposta é $n^2$; tente deduzir este valor formalmente).

In [149]:
import numpy as np

In [150]:
def solve_triangular_superior(U, b):
    '''Resolve um sistema triangular superior do tipo Ux = b.

    Parametros obrigatorios
    ----------
    U : Array-like de dimensao 2
        Matriz quadrada triangular superior inversível

    b : Array-like de dimensão 1
        Vetor independente

    Saída
    ----------
    x : Array-like de dimensão 1
        Solução do sistema Ux = b
    
    num_op : int 
        Número de operações'''

    num_op = 0
    n = U.shape[0]          # Ordem das matrizes
    
    # Cópias usuais para evitar problemas
    x = b.copy().reshape(n)

    # Vai linha-a-linha, de baixo para cima, escalonando a matriz utilizando o pivô na diagonal

    print("Inicio")
    print(x)
    print(U)
                        
    for i in range(n-1,-1,-1):
        x[i] /= U[i,i]     # Normaliza a i-ésima linha

        print(f"\nNormaliza")
        print(x)
        print("i:", i)

        num_op +=1
        for j in range(i-1,-1,-1):
            x[j] -= U[j,i]*x[i]     # Pivoteia a i-ésima coluna, utilizando a entrada diagonal como pivô
            print(f"\nPivoteada")
            print(f"i: {i}    j: {j}")
            print(f"x[{j}] -= U[{j},{i}]*x[{i}]")
            print(x)
            print(U)
            num_op += 2

    return x, num_op

In [151]:
tabela = []
ordem = 5
for tam in range(2, ordem+1):
    U = 20*np.random.rand(tam,tam) -10 # Matriz triangular aleatória com entradas em [-10,10]

    for i in range(tam):
        for j in range(i):
            U[i,j]=0.0        # Aniquila as entradas abaixo da diagonal principal para deixar triangular superior    
            
    b = 20*np.random.rand(tam) - 10 # Vetor aleatório com entradas em [-10,10]

    x, num_operacoes = solve_triangular_superior(U,b) # Solução pretendida do sistema Ux = b
    tabela.append([tam, num_operacoes])
    # print(f"\nA matriz U é dada por\n{U}")
    # print(f"\nO vetor b é dada por\n{b}")
    # print(f"\nO vetor x é dada por\n{x}")
    # print(f"\nO vetor Ux é dada por\n{U@x}")
    # print(f"---------------------------------")

# print(f"\nTabela relacionando a Ordem da matriz e o número de operações")
# print(f"\n|{'Ordem':^10}|{'Num. Op.':^10}|")

# for linha in tabela:    
#     print(f"|{linha[0]:^10}|{linha[1]:^10}|")

Inicio
[ 9.92269817 -8.75444279]
[[9.72747722 8.20653913]
 [0.         2.41989679]]

Normaliza
[ 9.92269817 -3.61769264]
i: 1

Pivoteada
i: 1    j: 0
x[0] -= U[0,1]*x[1]
[39.61143438 -3.61769264]
[[9.72747722 8.20653913]
 [0.         2.41989679]]

Normaliza
[ 4.07211793 -3.61769264]
i: 0
Inicio
[-8.69584049 -5.57791255  8.97339453]
[[-4.6724778  -3.83419907 -7.16452957]
 [ 0.         -9.13165897  0.29872857]
 [ 0.          0.          8.48284306]]

Normaliza
[-8.69584049 -5.57791255  1.05782866]
i: 2

Pivoteada
i: 2    j: 1
x[1] -= U[1,2]*x[2]
[-8.69584049 -5.89391619  1.05782866]
[[-4.6724778  -3.83419907 -7.16452957]
 [ 0.         -9.13165897  0.29872857]
 [ 0.          0.          8.48284306]]

Pivoteada
i: 2    j: 0
x[0] -= U[0,2]*x[2]
[-1.11699576 -5.89391619  1.05782866]
[[-4.6724778  -3.83419907 -7.16452957]
 [ 0.         -9.13165897  0.29872857]
 [ 0.          0.          8.48284306]]

Normaliza
[-1.11699576  0.64543762  1.05782866]
i: 1

Pivoteada
i: 1    j: 0
x[0] -= U[0,1]*x

> 2. Adapte o código acima para fazer o processo análogo (também contando operações), mas com matrizes triangulares _inferiores_.

In [152]:
def solve_triangular_inferior(L, b):
    '''Resolve um sistema triangular inferior do tipo Lx = b.

    Parametros obrigatorios
    ----------
    U : Array-like de dimensao 2
        Matriz quadrada triangular inferior inversível

    b : Array-like de dimensão 1
        Vetor independente

    Saída
    ----------
    x : Array-like de dimensão 1
        Solução do sistema Lx = b
    
    num_op : int 
        Número de operações'''

    num_op = 0
    n = L.shape[0]          # Ordem das matrizes
    
    # Cópias usuais para evitar problemas
    x = b.copy().reshape(n)
                        
    for i in range(n):
        for j in range(i):
            x[i] -= L[i][j] * x[j]
            num_op += 2
        x[i] /= L[i][i]
        num_op += 1
    return x, num_op

In [153]:
ordem = 3
L = 20*np.random.rand(ordem,ordem) -10 # Matriz triangular aleatória com entradas em [-10,10]
# print (U)
for i in range(ordem):
    for j in range(ordem-1, i, -1):
        L[i,j]=0.0        # Aniquila as entradas abaixo da diagonal principal para deixar triangular superior

print(L)


# print(U)    
        
b = 20*np.random.rand(ordem) - 10 # Vetor aleatório com entradas em [-10,10]

x, num_operacoes = solve_triangular_inferior(L,b) # Solução pretendida do sistema Ux = b

print(f"\nA matriz L é dada por\n{L}")
print(f"\nO vetor b é dada por\n{b}")
print(f"\nO vetor x é dada por\n{x}")
print(f"\nO vetor Lx é dada por\n{L@x}")

[[-6.22052231  0.          0.        ]
 [-5.15390569  2.91742902  0.        ]
 [ 6.44207234  7.50030318 -7.99039231]]

A matriz L é dada por
[[-6.22052231  0.          0.        ]
 [-5.15390569  2.91742902  0.        ]
 [ 6.44207234  7.50030318 -7.99039231]]

O vetor b é dada por
[0.8027004  7.88307859 1.79287726]

O vetor x é dada por
[-0.12904068  2.47410137  1.99393761]

O vetor Lx é dada por
[0.8027004  7.88307859 1.79287726]


> 3. Adapte o algoritmo de Crout&ndash;Dolittle, para fazer com que ele também retorne o número de operações realizadas.

In [154]:
def crout_dolittle(A):
    ''' Decomposição LU de A pelo algoritmo de Crout'''

    num_op = 0

    m,n = np.shape(A)

    L = np.zeros((n,n))
    U = np.zeros((n,n))

    L[0,0] = 1          # Escolha de Dolittle
    U[0,0] = A[0,0]

    for j in range(1,n):
        U[0,j] = A[0,j]/L[0,0]      # Determina a primeira linha de U
        L[j,0] = A[j,0]/U[0,0]      # Determina a primeira coluna de L
        num_op += 2
    
    for i in range(1,n):
        L[i,i]=1        # Escolha de Dolittle
        U[i,i] = A[i,i] - sum([L[i,k]*U[k,i] for k in range(i)])
        num_op += i + 1

        for j in range(i+1,n):
            U[i,j] = (A[i,j] - sum([L[i,k]*U[k,j] for k in range(i)]))/L[i,i]       # Determina a i-ésima linha de U
            L[j,i] = (A[j][i] - sum([L[j,k]*U[k,i] for k in range(i)]))/U[i,i]      # Determina a i-ésima coluna de L
            num_op += 2*(i + 2)
    return L , U, num_op

In [155]:
tabela = []
ordem = 10
for tam in range(2, ordem+1):
    A = 20*np.random.rand(tam, tam) - 10.0       # Matriz aleatória com entradas entre -10 e 10

    L , U, num_operacoes = crout_dolittle(A)               # Decomposição LU de $A$

    tabela.append([tam, num_operacoes])

    # print(f"A matriz A é dada por\n{A}")
    # print(f"\nA matriz L é dada por\n{L}")
    # print(f"\nA matriz U é dada por\n{U}")
    # print(f"\n\nO produto LU é dado por\n{L@U}")
    # print(f"---------------------------------")

print(f"\nTabela relacionando a Ordem da matriz e o número de operações")
print(f"\n|{'Ordem':^10}|{'Num. Op.':^10}|")

for linha in tabela:    
    print(f"|{linha[0]:^10}|{linha[1]:^10}|")


Tabela relacionando a Ordem da matriz e o número de operações

|  Ordem   | Num. Op. |
|    2     |    4     |
|    3     |    15    |
|    4     |    35    |
|    5     |    66    |
|    6     |   110    |
|    7     |   169    |
|    8     |   245    |
|    9     |   340    |
|    10    |   456    |


> 4. Utilize as funções criadas no passo anterior para criar uma função que recebe uma matriz $A$, um inteiro positivo $n$ e um vetor $b$ e
>     - Decompõe a matriz $A$ como $A=LU$.
>     - Resolve o sistema linear $A^n x = b$, com aplicações sucessivas das funções criadas nos passos 1. e 2.
>     - Conta o número de operações.

In [ ]:
def matmul(A,B):
    """Produto de matrizes quadradas de mesma ordem

    Parametros obrigatorios
    ----------
    A , B : Array-like de dimensao 2
        Matrizes quadradas de mesma ordem

    Saída
    ----------
    C : Array-like de dimensão 2
        Produto C = AB
        
    Num_operacoes : Numero de operacoes"""
    
    n=A.shape[0]
    
    C = np.zeros((n,n))
    
    for i in range(n):
        for j in range(n):
            for k in range(n):
                C[i,j] += A[i,k]*B[k,j]
                
    return C

In [156]:
def decompoe_matriz (A, n, b):
    '''Função decompor matriz em produto LU e calcular o sistema A^n x = b
    
    Parametros obrigatorios
    ----------
    A : Array-like
        Matriz quadrada

    n : int
        Valor do expoente no cálculo

    b : Array-like de dimensão 1
        Vetor independente'''
    num_op_total = 0
    print(f"A:\n", A)
    
    # Primeiro Item
    L, U, num_op = crout_dolittle(A)
    num_op_total += num_op
    print(f"\nLU:\n", L@U)

    # Segundo Item
    A_ = A.copy()
    for i in range(1, n):
        A_ = A_@A_
    print(f"A_^{n} = \n{A_}")






In [157]:
ordem = 2
A = 20*np.random.rand(ordem,ordem) -10 # Matriz triangular aleatória com entradas em [-10,10]
b = b = 20*np.random.rand(ordem) - 10 # Vetor aleatório com entradas em [-10,10]
n = 2

decompoe_matriz(A, n, b)

A:
 [[-8.70147332 -0.34333666]
 [ 3.36406583  7.00366124]]

LU:
 [[-8.70147332 -0.34333666]
 [ 3.36406583  7.00366124]]
1
A_^2 = 
[[74.56063085  0.58292112]
 [-5.71155162 47.8962636 ]]
